Homework14 Pavel Mitrafanau
Pavel2812mi/Mypymar2024 pull request #11
Opened 2024-06-21 15:51 UTC by Pavel2812mi

Good day, Sergei
My homework14 files are ready for review

2024-06-22 20:55 UTC, Stml89 requested changes

2024-06-22 20:55 UTC, Stml89 commented on Homework14_1.py
> +    with open("D:\\students.txt", "w", encoding="utf-8") as file:
Please do not use absolute path, because it will work for but not for other ppl: https://archive.ph/0aXb1

2024-06-26 10:55 UTC, Pavel2812mi commented
Absolute file path has been replaced with relative path, now should be fine

2024-06-28 20:34 UTC, Stml89 requested changes

2024-06-28 20:34 UTC, Stml89 commented on Homework14_1.py
Is that possible to use function(s) here?

2024-07-01 11:54 UTC, Pavel2812mi commented
I also updated the ruff linter launch command.

2024-07-01 20:44 UTC, Stml89 approved these changes

2024-07-01 20:45 UTC, Stml89 approved these changes

2024-07-02 20:57 UTC, merged