Homework21: Pavel Mitrafanau
Pavel2812mi/Mypymar2024 pull request #13
Opened 2024-07-19 19:36 UTC by Pavel2812mi

Good day, Sergey.
Made test cases (test folder) to check the operation of library and bank deposits modules (source folder, also i added all previous homework modules into it )
​​​Pylint error W0201 occurs in test_bank_deposit, I haven’t found a way to fix it yet, so I temporarily added it to the exceptions

2024-07-19 20:55 UTC, Pavel2812mi commented
HTML report with test results added to the project tests folder

2024-07-20 11:35 UTC, Pavel2812mi commented
Fixed pylint E0401 error, all is correct now

2024-07-20 19:52 UTC, Stml89 requested changes

2024-07-20 19:52 UTC, Stml89 commented on homework21/tests/test_library.py
> +    logger.add(log_file, level=log_level, enqueue=True)
You can use 1 logger across a single application, e.g.: https://stackoverflow.com/questions/75489656/how-to-use-a-single-python-logging-object-throughout-the-python-application

2024-07-21 13:43 UTC, Pavel2812mi commented
Added single logger for test_library and for test_bank_deposit modules

2024-07-23 19:14 UTC, Stml89 requested changes

2024-07-23 19:14 UTC, Stml89 commented on homework21/tests/test_library.py
> +logger.add(log_file, level="DEBUG", enqueue=True)
It is better this time, but I saw the same lines in `homework21/tests/test_bank_deposit.py` file. Better to use 1 file where you setup a logger, in test modules you will ned hust import it and use
https://stackoverflow.com/questions/75489656/how-to-use-a-single-python-logging-object-throughout-the-python-application

2024-07-26 10:20 UTC, Pavel2812mi commented
Made silngle logger file in tests folder with logging settings

2024-07-27 15:05 UTC, Stml89 approved these changes

2024-07-27 18:18 UTC, merged