Homework22: Pavel Mitrafanau
Pavel2812mi/Mypymar2024 pull request #14
Opened 2024-07-23 23:32 UTC by Pavel2812mi

Good day, Sergei
My robot framework tests are ready for review

2024-07-24 09:01 UTC, Stml89 approved these changes

2024-07-24 09:01 UTC, Stml89 commented on library_keywords.py
> +    return Reader(name=name)
```suggestion
    return Reader(name)
```

2024-07-24 09:04 UTC, Stml89 requested changes

2024-07-24 09:04 UTC, Stml89 commented on bank_deposit_robot.robot
Can not find any logging here

2024-07-24 09:04 UTC, Stml89 commented on library_keywords.py
Can not find any logging here

2024-07-25 11:22 UTC, Pavel2812mi commented
Logging added to library and bank deposit tests

2024-07-27 15:33 UTC, Stml89 approved these changes
Good project structure: https://docs.robotframework.org/docs/examples/project_structure#examples

2024-07-28 20:08 UTC, merged