Homework7: Pavel Mitrafanau
Pavel2812mi/Mypymar2024 pull request #5
Opened 2024-05-24 17:53 UTC by Pavel2812mi

Hello, Sergei 
This homework was an uneasy one, but I think I did it 
Please check if everything is correct

2024-05-28 20:13 UTC, Stml89 requested changes

2024-05-28 20:13 UTC, Stml89 commented on Homework7.py
> +    for i in range(len(str(number))):
Calculations does not work correctly, try:
random number:3649
guess: 3694

2024-05-28 20:13 UTC, Stml89 commented on Homework7.py
> +    number = int(input("Введите ваше число: "))
it is possible to enter non unique number

2024-05-28 22:35 UTC, Pavel2812mi commented
Code fixed, please review again

2024-05-29 20:13 UTC, Stml89 reviewed
You can merge it

2024-05-29 20:13 UTC, Stml89 commented on Homework7.py
> +# pylint: disable=invalid-name
remove it

2024-05-29 20:13 UTC, Stml89 commented on Homework7.py
> +# Начинаем цикл угадывания (загаданное число при этом не меняется)
do not need to comment obvious actions

2024-05-30 10:15 UTC, merged