Homework11: Pavel Mitrafanau
Pavel2812mi/Mypymar2024 pull request #9
Opened 2024-06-13 14:24 UTC by Pavel2812mi

Good day, Sergei
My homework11 file is ready for review

2024-06-16 08:45 UTC, Stml89 requested changes

2024-06-16 08:45 UTC, Stml89 commented on Homework11_1.py
> +class reader:
Class name starts with upper letter: `Reader`

2024-06-16 08:45 UTC, Stml89 commented on Homework11_1.py
> +        self.taken_books = taken_books
```suggestion
        self.resereved_books = []
        self.taken_books = []
```

2024-06-16 08:45 UTC, Stml89 commented on Homework11_1.py
> +    reserved_books: list["Book"] = []
```suggestion
from typing import List

...
reserved_books: List[str] = []
```

2024-06-16 08:45 UTC, Stml89 commented on Homework11_2.py
> +client1.create_deposit("Deposit_1", 1000, 2, 10)
if a user puts 1000 for 1 year, with 10% -> he should get ~1104.** after 1 year

2024-06-16 21:35 UTC, Pavel2812mi commented
The requested changes have been made to the code for Homework11_1 and Homework11_2.

2024-06-17 17:33 UTC, Stml89 approved these changes

2024-06-17 20:38 UTC, merged